---
# tasks file for ansible-role-packer

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Include OS specific variables."
  include_vars: "{{ ansible_system }}.yml"
  when: packer_install

- name: "{{ ansible_distribution | lower }} | {{ ansible_distribution_release }} - Install Packer"
  include_tasks: "setup-{{ ansible_system }}.yml"
  when: packer_install
